export const styles = {
  page: {
    minHeight: "100vh",
    bgcolor: "#f8fafc",
    color: "#0f172a",
    fontFamily: "'Manrope', 'Sora', 'Nunito Sans', sans-serif",
  },
  heroShell: {
    position: "relative",
    overflow: "hidden",
    background:
      "linear-gradient(145deg, #111d46 0%, #1f2b5f 52%, #2563eb 100%)",
    color: "#f8fafc",
    pb: { xs: 6, md: 8 },
  },
  glowA: {
    position: "absolute",
    width: 280,
    height: 280,
    borderRadius: "50%",
    top: -110,
    right: -60,
    background: "radial-gradient(circle, rgba(245,158,11,0.4), transparent 68%)",
    pointerEvents: "none",
  },
  glowB: {
    position: "absolute",
    width: 320,
    height: 320,
    borderRadius: "50%",
    bottom: -170,
    left: -140,
    background: "radial-gradient(circle, rgba(255,255,255,0.25), transparent 65%)",
    pointerEvents: "none",
  },
  topBar: {
    py: 2.2,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 1.5,
    flexWrap: "wrap",
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: 1,
    fontWeight: 800,
    letterSpacing: "0.03em",
  },
  heroGrid: {
    mt: { xs: 2, md: 3 },
    display: "grid",
    gridTemplateColumns: { xs: "1fr", md: "1.05fr 0.95fr" },
    gap: 3,
    alignItems: "center",
  },
  heroTitle: {
    fontSize: { xs: "2rem", md: "3rem" },
    lineHeight: 1.1,
    fontWeight: 800,
    letterSpacing: "-0.02em",
    maxWidth: 640,
  },
  heroText: {
    mt: 2,
    maxWidth: 560,
    color: "rgba(248,250,252,0.94)",
    fontSize: { xs: "0.98rem", md: "1.06rem" },
    lineHeight: 1.75,
  },
  heroActions: {
    mt: 3,
    display: "flex",
    gap: 1.1,
    flexWrap: "wrap",
  },
  primaryBtn: {
    px: 3.2,
    py: 1.2,
    borderRadius: "999px",
    backgroundColor: "#f8fafc",
    color: "#111d46",
    fontWeight: 800,
    "&:hover": { backgroundColor: "#e2e8f0" },
  },
  secondaryBtn: {
    px: 3.2,
    py: 1.2,
    borderRadius: "999px",
    borderColor: "rgba(248,250,252,0.72)",
    color: "#f8fafc",
    fontWeight: 700,
    "&:hover": {
      borderColor: "#f8fafc",
      backgroundColor: "rgba(248,250,252,0.12)",
    },
  },
  heroCard: {
    borderRadius: 3.2,
    p: 2,
    border: "1px solid rgba(255,255,255,0.28)",
    background: "rgba(255,255,255,0.1)",
    backdropFilter: "blur(6px)",
  },
  heroCardRow: {
    p: 1.2,
    borderRadius: 2,
    border: "1px solid rgba(255,255,255,0.2)",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  section: {
    py: { xs: 7, md: 8 },
  },
  sectionHeading: {
    fontWeight: 800,
    color: "#1f2b5f",
    fontSize: { xs: "1.55rem", md: "1.9rem" },
    mb: 1,
  },
  sectionSub: {
    color: "#475569",
    lineHeight: 1.7,
    mb: 3.5,
    maxWidth: 700,
  },
  categoryCard: {
    height: "100%",
    borderRadius: 3,
    border: "1px solid #e2e8f0",
    boxShadow: "0 10px 26px rgba(15,23,42,0.07)",
    backgroundColor: "#ffffff",
  },
  categoryImage: {
    width: "100%",
    height: 140,
    objectFit: "cover",
    borderBottom: "1px solid #e2e8f0",
    backgroundColor: "#e2e8f0",
  },
  categoryBody: {
    p: 2,
  },
  infoGrid: {
    display: "grid",
    gridTemplateColumns: { xs: "1fr", md: "repeat(3,1fr)" },
    gap: 1.4,
  },
  infoCard: {
    p: 2,
    borderRadius: 2.6,
    border: "1px solid #e2e8f0",
    backgroundColor: "#ffffff",
  },
};
